name: "Blog of Youngeyes"
description: "Web Front-End Blog by Youngeyes"

url: "https://youngeyes.github.io/Blog"
loadingImg: "https://youngeyes.github.io/Blog/img/loading.gif"
filePath: "https://youngeyes.github.io/Blog/img"

timezone: Asia/Shanghai

paginate: 16
paginate_path: "/page:num"

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

permalink: pretty

gems:
- jekyll-paginate
