name: "Blog of Youngeyes"
description: "Web Front-End Blog by Youngeyes"

url: "http://youngeyes.github.io/Blog/"
loadingImg: "http://youngeyes.github.io/Blog/img/loading.gif"
filePath: "http://youngeyes.github.io/Blog/img/"

timezone: Asia/Shanghai

paginate: 16
paginate_path: "/page:num"

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

permalink: pretty

gems:
- jekyll-paginate
